import XCTest

final class ContentViewContractTests: XCTestCase {
    func testContentViewContainsTabbedWorkbenchContract() throws {
        let source = try String(contentsOf: contentViewURL, encoding: .utf8)

        XCTAssertTrue(source.contains("ConnectionWorkspaceStore"))
        XCTAssertTrue(source.contains("tabStrip"))
        XCTAssertTrue(source.contains("addSQLTab"))
        XCTAssertTrue(source.contains("Table Explorer"))
        XCTAssertTrue(source.contains("QueryResultGrid"))
        XCTAssertTrue(source.contains("executeQuery"))
        XCTAssertTrue(source.contains("showingNewConnection"))
        XCTAssertTrue(source.contains("NewConnectionView"))
        XCTAssertTrue(source.contains("Image(systemName: \"plus\")"))
        XCTAssertTrue(source.contains("createConnection"))
        XCTAssertTrue(source.contains(".navigationSplitViewColumnWidth(min: 220, ideal: 260, max: 360)"))
        XCTAssertTrue(source.contains("Table(tables, selection:"))
        XCTAssertTrue(source.contains("loadTableSchema"))
        XCTAssertTrue(source.contains("previewSelectedTable"))
        XCTAssertTrue(source.contains("loadSchema(connectionID:"))
        XCTAssertTrue(source.contains("previewTable("))
        XCTAssertTrue(source.contains("maxRows: 50"))
        XCTAssertTrue(source.contains(".task(id: store.selectedConnectionID)"))
        XCTAssertTrue(source.contains("openSelectedConnection"))
        XCTAssertTrue(source.contains("openConnection(connectionID:"))
        XCTAssertTrue(source.contains("@State private var selectedRowID: QueryResultTableRow.ID?"))
        XCTAssertTrue(source.contains("@State private var rowDetailSelection: RowDetailSelection?"))
        XCTAssertTrue(source.contains("@State private var rowDetailClearID = UUID()"))
        XCTAssertTrue(source.contains(".overlay(alignment: .trailing)"))
        XCTAssertTrue(source.contains("workspaceRowDetailPanel"))
        XCTAssertTrue(source.contains("visibleRowDetailSelection"))
        XCTAssertTrue(source.contains("RowDetailSelection("))
        XCTAssertTrue(source.contains("let onInspectRow: (RowDetailSelection) -> Void"))
        XCTAssertTrue(source.contains("let onCloseInspector: () -> Void"))
        XCTAssertTrue(source.contains("let clearSelectionID: UUID"))
        XCTAssertTrue(source.contains("clearSelectionID: rowDetailClearID"))
        XCTAssertTrue(source.contains(".onChange(of: clearSelectionID) { _, _ in"))
        XCTAssertTrue(source.contains("onInspectRow: { selection in"))
        XCTAssertTrue(source.contains("onCloseInspector: clearRowDetailSelection"))
        XCTAssertTrue(source.contains("private func visibleResultID("))
        XCTAssertTrue(source.contains("Table(resultRows, selection: $selectedRowID)"))
        XCTAssertTrue(source.contains("RowDetailInspector"))
        XCTAssertTrue(source.contains("showInspector(for:"))
        XCTAssertTrue(source.contains("if let newValue {"))
        XCTAssertTrue(source.contains("showInspector(for: newValue)"))
        XCTAssertTrue(source.contains("resultID: resultID"))
        XCTAssertTrue(source.contains(".id(resultID)"))
        XCTAssertTrue(source.contains("let resultID: UUID"))
        XCTAssertTrue(source.contains("clearSelection"))
        XCTAssertTrue(source.contains("guard let selectedRow = resultRows.first"))
        XCTAssertTrue(source.contains("selectedRowID = nil"))
        XCTAssertTrue(source.contains("rowDetailClearID = UUID()"))
        XCTAssertTrue(source.contains("Close Details"))
        XCTAssertTrue(source.contains("row.value(at: index)"))
        XCTAssertFalse(source.contains("HSplitView"))
        XCTAssertFalse(source.contains("Grid(alignment: .leading"))
    }

    private var contentViewURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Sources/CosmicDataExplorerMacCore/ContentView.swift")
    }
}
